using System.Collections.Generic;

namespace MeloncherCore.Options
{
	internal static class McKeycodes
	{
		private static readonly Dictionary<string, int> Dict = new()
		{
			{"key.keyboard.unknown", 0},
			{"key.mouse.left", -100},
			{"key.mouse.right", -99},
			{"key.mouse.middle", -98},
			{"key.mouse.4", -97},
			{"key.mouse.5", -96},
			{"key.mouse.6", -95},
			{"key.mouse.7", -94},
			{"key.mouse.8", -93},
			{"key.keyboard.0", 11},
			{"key.keyboard.1", 2},
			{"key.keyboard.2", 3},
			{"key.keyboard.3", 4},
			{"key.keyboard.4", 5},
			{"key.keyboard.5", 6},
			{"key.keyboard.6", 7},
			{"key.keyboard.7", 8},
			{"key.keyboard.8", 9},
			{"key.keyboard.9", 10},
			{"key.keyboard.a", 30},
			{"key.keyboard.b", 48},
			{"key.keyboard.c", 46},
			{"key.keyboard.d", 32},
			{"key.keyboard.e", 18},
			{"key.keyboard.f", 33},
			{"key.keyboard.g", 34},
			{"key.keyboard.h", 35},
			{"key.keyboard.i", 23},
			{"key.keyboard.j", 36},
			{"key.keyboard.k", 37},
			{"key.keyboard.l", 38},
			{"key.keyboard.m", 50},
			{"key.keyboard.n", 49},
			{"key.keyboard.o", 24},
			{"key.keyboard.p", 25},
			{"key.keyboard.q", 16},
			{"key.keyboard.r", 19},
			{"key.keyboard.s", 31},
			{"key.keyboard.t", 20},
			{"key.keyboard.u", 22},
			{"key.keyboard.v", 47},
			{"key.keyboard.w", 17},
			{"key.keyboard.x", 45},
			{"key.keyboard.y", 21},
			{"key.keyboard.z", 44},
			{"key.keyboard.f1", 59},
			{"key.keyboard.f2", 60},
			{"key.keyboard.f3", 61},
			{"key.keyboard.f4", 62},
			{"key.keyboard.f5", 63},
			{"key.keyboard.f6", 64},
			{"key.keyboard.f7", 65},
			{"key.keyboard.f8", 66},
			{"key.keyboard.f9", 67},
			{"key.keyboard.f10", 68},
			{"key.keyboard.f11", 87},
			{"key.keyboard.f12", 88},
			{"key.keyboard.f13", 100},
			{"key.keyboard.f14", 101},
			{"key.keyboard.f15", 102},
			{"key.keyboard.f16", 103},
			{"key.keyboard.f17", 104},
			{"key.keyboard.f18", 105},
			{"key.keyboard.f19", 113},
			{"key.keyboard.num.lock", 69},
			{"key.keyboard.keypad.0", 82},
			{"key.keyboard.keypad.1", 79},
			{"key.keyboard.keypad.2", 80},
			{"key.keyboard.keypad.3", 81},
			{"key.keyboard.keypad.4", 75},
			{"key.keyboard.keypad.5", 76},
			{"key.keyboard.keypad.6", 77},
			{"key.keyboard.keypad.7", 71},
			{"key.keyboard.keypad.8", 72},
			{"key.keyboard.keypad.9", 73},
			{"key.keyboard.keypad.add", 78},
			{"key.keyboard.keypad.decimal", 83},
			{"key.keyboard.keypad.enter", 28},
			{"key.keyboard.keypad.equal", 141},
			{"key.keyboard.keypad.multiply", 55},
			{"key.keyboard.keypad.divide", 181},
			{"key.keyboard.keypad.subtract", 74},
			{"key.keyboard.down", 208},
			{"key.keyboard.left", 203},
			{"key.keyboard.right", 205},
			{"key.keyboard.up", 200},
			{"key.keyboard.apostrophe", 40},
			{"key.keyboard.backslash", 43},
			{"key.keyboard.comma", 51},
			{"key.keyboard.equal", 13},
			{"key.keyboard.grave.accent", 41},
			{"key.keyboard.left.bracket", 26},
			{"key.keyboard.minus", 12},
			{"key.keyboard.period", 52},
			{"key.keyboard.right.bracket", 27},
			{"key.keyboard.semicolon", 39},
			{"key.keyboard.slash", 53},
			{"key.keyboard.space", 57},
			{"key.keyboard.tab", 15},
			{"key.keyboard.left.alt", 56},
			{"key.keyboard.left.control", 29},
			{"key.keyboard.left.shift", 42},
			{"key.keyboard.left.win", 219},
			{"key.keyboard.right.alt", 184},
			{"key.keyboard.right.control", 157},
			{"key.keyboard.right.shift", 54},
			{"key.keyboard.right.win", 220},
			{"key.keyboard.enter", 28},
			{"key.keyboard.escape", 1},
			{"key.keyboard.backspace", 14},
			{"key.keyboard.delete", 211},
			{"key.keyboard.end", 207},
			{"key.keyboard.home", 199},
			{"key.keyboard.insert", 210},
			{"key.keyboard.page.down", 209},
			{"key.keyboard.page.up", 201},
			{"key.keyboard.caps.lock", 58},
			{"key.keyboard.pause", 197},
			{"key.keyboard.scroll.lock", 70},
			{"key.keyboard.menu", 221},
			{"key.keyboard.print.screen", 183}
		};

		public static bool Contains(string key)
		{
			return Dict.ContainsKey(key);
		}

		public static int Get(string key)
		{
			return Dict[key];
		}
	}
}