//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeloncherAvalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeloncherAvalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Microsoft.
        /// </summary>
        public static string AddMicrosoftAccount {
            get {
                return ResourceManager.GetString("AddMicrosoftAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;re done, copy your browser address bar here and click Add.
        /// </summary>
        public static string AddMicrosoftDialogText {
            get {
                return ResourceManager.GetString("AddMicrosoftDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mojang.
        /// </summary>
        public static string AddMojangAccount {
            get {
                return ResourceManager.GetString("AddMojangAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offline.
        /// </summary>
        public static string AddOfflineAccount {
            get {
                return ResourceManager.GetString("AddOfflineAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from .minecraft.
        /// </summary>
        public static string ImportSettings {
            get {
                return ResourceManager.GetString("ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs (Beta).
        /// </summary>
        public static string LogsTabTitle {
            get {
                return ResourceManager.GetString("LogsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max RAM.
        /// </summary>
        public static string MaxRam {
            get {
                return ResourceManager.GetString("MaxRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ModPack.
        /// </summary>
        public static string ModPackCreate {
            get {
                return ResourceManager.GetString("ModPackCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ModPack.
        /// </summary>
        public static string ModPackEdit {
            get {
                return ResourceManager.GetString("ModPackEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPack folder.
        /// </summary>
        public static string ModPackFolder {
            get {
                return ResourceManager.GetString("ModPackFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ModPack.
        /// </summary>
        public static string ModPackRemove {
            get {
                return ResourceManager.GetString("ModPackRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPacks (Beta).
        /// </summary>
        public static string ModPackTabTitle {
            get {
                return ResourceManager.GetString("ModPackTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected account.
        /// </summary>
        public static string RemoveSelectedAccount {
            get {
                return ResourceManager.GetString("RemoveSelectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected account.
        /// </summary>
        public static string SelectedAccount {
            get {
                return ResourceManager.GetString("SelectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected version.
        /// </summary>
        public static string SelectedVersion {
            get {
                return ResourceManager.GetString("SelectedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version.
        /// </summary>
        public static string SelectVersion {
            get {
                return ResourceManager.GetString("SelectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        public static string Snapshots {
            get {
                return ResourceManager.GetString("Snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Optifine.
        /// </summary>
        public static string UseOptifine {
            get {
                return ResourceManager.GetString("UseOptifine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use transparency.
        /// </summary>
        public static string UseTransparency {
            get {
                return ResourceManager.GetString("UseTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window mode.
        /// </summary>
        public static string WindowMode {
            get {
                return ResourceManager.GetString("WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string WindowModeBorderless {
            get {
                return ResourceManager.GetString("WindowModeBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string WindowModeFullscreen {
            get {
                return ResourceManager.GetString("WindowModeFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string WindowModeWindowed {
            get {
                return ResourceManager.GetString("WindowModeWindowed", resourceCulture);
            }
        }
    }
}
