//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeloncherAvalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeloncherAvalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs (Beta).
        /// </summary>
        public static string LogsTabTitle {
            get {
                return ResourceManager.GetString("LogsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ModPack.
        /// </summary>
        public static string ModPackCreate {
            get {
                return ResourceManager.GetString("ModPackCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ModPack.
        /// </summary>
        public static string ModPackEdit {
            get {
                return ResourceManager.GetString("ModPackEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPack folder.
        /// </summary>
        public static string ModPackFolder {
            get {
                return ResourceManager.GetString("ModPackFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ModPack.
        /// </summary>
        public static string ModPackRemove {
            get {
                return ResourceManager.GetString("ModPackRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPacks (Beta).
        /// </summary>
        public static string ModPackTabTitle {
            get {
                return ResourceManager.GetString("ModPackTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected account.
        /// </summary>
        public static string SelectedAccount {
            get {
                return ResourceManager.GetString("SelectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected version.
        /// </summary>
        public static string SelectedVersion {
            get {
                return ResourceManager.GetString("SelectedVersion", resourceCulture);
            }
        }
    }
}
