rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\cs\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\de\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\es\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\fr\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\it\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\ja\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\ko\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\pl\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\pt-BR\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\ru\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\tr\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\zh-Hans\"
rd /s /q "..\src\MeloncherAvalonia\bin\Release\net5.0\win-x86\zh-Hant\"

"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "Meloncher.iss"